### ISSUE TITLE
[FEAT] 게임 타이틀 HUD 작성

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#17]
## Description

- 게임 타이틀 HUD 작성
- 게임 시작 클릭 시 각종 효과에 대한 애니메이션 재생

## TODO

- [x] WBP_Title 생성
- [x] 게임 로고, 시작, 종료 버튼 할당
- [x] 배경 블러 할당
- [x] 게임 시작 버튼 클릭 시 UI가 사라지는 애니메이션 재생
