### ISSUE TITLE
[FEAT] 3개의 임시 스테이지 레벨디자인

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#21]
## Description

- 베타 버전까지 사용할 임시 스테이지 3개 레벨 디자인

## TODO

- [x] House Map 디자인
- [x] Subway Map 디자인
- [x] Container Map 디자인
