### ISSUE TITLE
[FEAT] 메인 WBP 디자인 완성

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#27]
## Description
- 메인 UI WBP 디자인 및 필요 연출 메서드 작성 완료

## TODO
- [x] WBP 에셋 교체 및 디자인
- [x] 톱니 회전 메서드 작성
- [x] 레벨업 바 등장 메서드 작성

## Reference
- 주로 Synty 아포칼립스 HUD 에셋 사용
