### ISSUE TITLE
[FEAT] Logic - UI 연동

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#43]
## Description

- 악세사리, 스탯, 레벨과 경험치 로직을 UI와 연결

## TODO

- [x] 악세사리 UI 연동
- [x] 스탯 UI 연동
- [x] 레벨과 경험치 UI 연동

## Additional context

- 9월 20일 저녁부터 화상회의를 통해 실시간 진행
