### ISSUE TITLE
[FEAT] 던전 클리어시 보상 지급 시스템

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#44]
## Description

던전 클리어 시 보상을 지급하는 시스템

## TODO

- [x] 보상 테이블에 대한 Enum 정의
- [x] 아이템 타입 정의
- [ ] 던전 클리어 이벤트 발생 시 보상 지급 트리거 발동
- [ ] 확률적 보상 테이블에 따른 지급 아이템 확정 로직

## Reference

![image](https://github.com/user-attachments/assets/4db5c574-4722-420c-aea5-004c01db0f83)

- 상점에서 판매중인 아이템의 자물쇠 효과는 위젯 컴포넌트 UI로 해결

## Additional context

- 던전 클리어 시 보상 지급 로직과 별개로 실제 게임 레벨에 3D 아이템 오브젝트가 등장 및 처리되려면, 아이템 오브젝트의 상태나 상점에서의 아이템 상태 등이 모두 정의되어있어야 함.
