### ISSUE TITLE
[FEAT] 좀비 구역 게임 시작 / 게임 클리어

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#5]
## Description

- 좀비 구역에서 정해진 시간만큼 좀비가 스폰된 뒤, 모두 물리쳤다면 게임을 클리어하는 기능

## TODO

- [x] 10초동안 좀비가 지속적으로 다양한 스폰포인트에서 일정한 스폰 주기를 가지고 스폰 (해당 10초는 가변적임)
- [x] 남은 시간이 00:00에 도달하면 맵 중앙에 포탈(발판) 생성
- [x] 플레이어와 발판이 충돌하면 맵 리스타트 (다음 맵으로 넘어가는 듯)

**Comment by kangtoe** [comment]
기획에서 변경된 사항 수정 부탁합니다!

**Comment by kangtoe** [comment]
6a5e519 커밋에서 해당 사항은 해결된것 같습니다! 이슈 Close하면 어떨까요..?
