### ISSUE TITLE
[FEAT] 아이템 상호작용 UI

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#51]
## Description

- 상자 / 아이템에 가까이 다가가 상호작용을 할 때 떠야 하는 UI
- F를 눌러 획득 / 열기 / 확인 등등

## TODO

- [x] 무기 상호작용 UI
- [x] 악세사리 상호작용 UI
- [x] 골드 상호작용 UI
- [x] 상자 상호작용 UI

## Reference

![image](https://github.com/user-attachments/assets/7333115e-f12a-4cc4-99b3-eae975db44e1)
