### ISSUE TITLE
[FEAT] 다음 맵 정보 안내 이정표

### ISSUE THREAD

**Issue by Suldangoo** [Controller-Team/UNDEADER#52]
## Description

- 돌기둥 위에 상징적인 오브젝트를 배치하며 다음 맵에 대한 정보 제공

## TODO

- [ ] 초록색 빛 해골 : 평범 좀비 구역
- [ ] 주황색 빛 해골 : 위험 좀비 구역
- [ ] 빨간색 빛 해골 : 혼돈 좀비 구역
- [ ] 골드와 포션 몇 개 : 상점 구역
- [ ] 분수 등의 조형 : 휴식 구역
